GRANT FILE ON *.* TO 'etl_app_user'@'%';
GRANT
  SELECT,
  RELOAD,
  FLUSH_TABLES,
  SHOW DATABASES,
  REPLICATION SLAVE,
  REPLICATION CLIENT,
  LOCK TABLES
 ON *.* TO 'etl_app_user'@'%';
FLUSH PRIVILEGES;
